seleniumhub:
  image: selenium/hub:3.0.0-cerium
  ports:
    - 4444:4444

firefoxnode:
  image: selenium/node-firefox:3.0.0-cerium
  ports:
    - 5900
  links:
    - seleniumhub:hub

chromenode:
  image: selenium/node-chrome:3.0.0-cerium
  ports:
    - 5900
  links:
    - seleniumhub:hub